version: '3'

services:
  burger-service:
    container_name: burger-service
    image: burger-service:latest
    depends_on:
      - nginx
    volumes:
      - ./src:/var/www/html
    ports:
      - 587:587
  
  nginx:
    image: nginx:1.19
    restart: unless-stopped
    volumes:
      - ./src:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:80
  
  mysql:
    image: mysql:5.7.22
    command: --explicit_defaults_for_timestamp
    container_name: mysqldb
    restart: unless-stopped
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: burgerservice
      MYSQL_USER: homestead
      MYSQL_PASSWORD: secret
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - 3306:3306

  composer:
    image: composer:latest
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html

  artisan:
    image: burger-service:latest
    working_dir: /var/www/html
    entrypoint: ['php', 'artisan']
    depends_on:
      - mysql
    volumes:
      - ./src:/var/www/html